### PR TITLE
Fix incomplete socket read

### PR DESCRIPTION
**Pull request by cavanierc**
The rendered MJML templates is sometimes truncated specially when the message is more than 60KB.
The issue comes from the fact that a socket does not guaranteed to receive the whole message and may return partial message.

This PR received from the socket until the message is completed before processing. A length marker was added to the message from django-mjml to tcpserver which create a compatibility break.

### CODE REVIEW

**Comment by cavanierc** [comment]
Hello, did you look at my request?
Thank you

**Comment by liminspace** [comment]
Yes, I've seen your request, but I'm busy at this time. I'll review and update django-mjml as soon as I can. Thank you.

**Comment by liminspace** [comment]
@cavanierc, hi, I've fixed this bug. Can you review my js code and check the solution?
https://github.com/liminspace/django-mjml/commit/b09d627d815194b8caf285e2c0780ad8f096cab4
It is similar to your one but I wrote it in my own way :)

**Comment by cavanierc** [comment]
With PR #17, it's good for me.

**Pull request closed without merging**
