### PR TITLE
WIP: Allow Django 4.2 (and 4.2rc1).

### PR DESCRIPTION
**Pull request by mvaled**

### CODE REVIEW

**Comment by mvaled** [comment]
Hi @liminspace,

Please take a look at this PR.  AFAIK Django 4.2 doesn't break this package.

**Comment by kenneweg** [comment]
+1 4.2 officially released please update your package

**Comment by liminspace** [comment]
Hi guys, thanks for your activity. I'll update the package this week.

**Comment by liminspace** [comment]
Version 1.1 has been released.

**Pull request closed without merging**
