### PR TITLE
Use TemporaryFile for stdout to support large emails

### PR DESCRIPTION
**Pull request by nickday**
I ran into an issue where my email was getting cut off somewhere in the middle of the HTML. It turns out it was over 65kb, which I guess is the limit for `subprocess.PIPE` where `stdout` is being redirected to - so I switched this to a `TemporaryFile`.

### CODE REVIEW

**Comment by liminspace** [comment]
Hi Nick Day, thanks for your update! I'll check it and release this fix in a month and a half.

**Comment by sklarsa** [comment]
What's the status on this fix? We're getting bitten by this same issue and would love a quick resolution if possible!  Thanks!

**Comment by sklarsa** [comment]
@liminspace the rendering performance is not a huge concern since we are not sending a significant amount of emails.  Also, we don't want to incur the additional cost of spinning up a server (along with orchestrating and securing it) just to render a few emails.  Would it be possible to at least accept the pull request so we can include the commit in our python dependencies?

Thanks!

**Comment by liminspace** [comment]
@sklarsa you can temporary use this version https://github.com/nickday/django-mjml/tree/master if it works for you correctly. 
I must added that using `tcpserver mode` must be cheaper than `cmd mode` because it keep mjml in memory and not restart it all time. It's very simple to use docker for it. There is the container with mjml that is working well `liminspace/mjml-tcpserver`.

**Comment by sklarsa** [comment]
Ah understood! Thanks!

**Comment by liminspace** [comment]
I've added test case to test a big mjml-template (5 Mb) and I see that problem is only for mjml v3.3.5 https://travis-ci.org/liminspace/django-mjml/builds/443788636
I think it is not Python problem. And I don't know if there is a reason to fix this problem for mjml v3.3.5 as it is old version.
Please, update to mjml v4.1.2 and check.

**Comment by liminspace** [comment]
Using temporary file is not a good idea as it is disk-IO-operation that increase overhead.

**Comment by liminspace** [comment]
As `cmd mode` is not a production mode I added using `TemporaryFile` for `stdout`. It is an easier solution than using a subprocess for stdout reading.

**Comment by liminspace** [comment]
Version 0.5.4 was released.

**Pull request closed without merging**
