### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by liminspace**
* Added supporting Django v3.2
 * Added Python 3.9 in tests
 * Added MJML 4.10.1 in tests
 * Removed Python 3.5 from tests
 * Removed MJML older than 4.4.0 from tests
 * Upgraded Node to v14 for tcp-server
 * Upgraded MJML to 4.9.3 in dockerfile
 * Moved from Travis to GitHub Actions

### CODE REVIEW

**Comment by ronaldgrn** [comment]
Brilliant. Thanks for this.

**Comment by j0nm1** [comment]
Hi, is there an estimated date when this will be merged? I would like to update my applications to Django 3.2 but this is blocked at the moment.

**Comment by liminspace** [comment]
I planned finish it by the end of next week

**Comment by ronaldgrn** [comment]
@j0nm1 If you're blocked you can always specify the commit.

```
pip install git+https://github.com/liminspace/django-mjml.git@7bb97b78b6554de3afcf96c61bd43f359cb62f58
```

**Comment by j0nm1** [comment]
@liminspace Ok, thank you!
@ronaldgrn Thanks for your advice but this is more like a workaround and nothing that can be used in production.

**Pull request merged**
